dist: xenial
language: generic
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps
before_deploy:
- bash scripts/deploy.sh
deploy:
  provider: releases
  api_key:
    secure: YswUO25BWkIjD9uK1RYUI/+fu3e2DS/R5y/MoJTWoTOajPhVBBeVGQp/ACJ4Q/V/Brpxxz6B5MsxRMpcxPRhZu2Dfou9ag2HniBdtGNQw9SDyoNtjp9d8gxIvLySpP97qnjuDs24WoxriNNbd1RHfn9GKrkJOMgmliR9bFhDfzdrCyZUVUf3Q749nMuTyf9R1KBgU64/w0l4w/4gaUNrUkjkh/6NhkUYJbxoaGfCNvM9wUy2SETP+FJcWbMvD/J5kwW3g8W/Fa8fXCZHG3QO1QPPwm1kTrZa85SicvAt0JoiOl6Uf4/DzVkj84GlA0Ccn6dSuIjf2Rtdi3fqEgDHEi9xMH2CIs6xo8oP4ogSDLJ1cXwLwQWqy3U0bU9+SopShLLIDzJoyx9UM/fTyTlxf7jSv7YdqglFwP55FayDqhkw86dvu1/uKW/7yPRcKiw6wFy+4+dRNzItVzqCDhQ1G37NQi/D2/Khvh8nDfukfdrmiYTEhwIvtW09HAQhMvm033RzBH4YiWZ9i9QgdBk7Rnc5yK3jZvchWCV6SWpNqGqOX0lpdCar1qiLYixTg9fagKVmZ7gA5atKQlIqusXc6bu3QU8f/UHf1VThqoXxYPIcXH4ziPP9vS6Jv1/78MegS6WAcbk2vRWcoh1270dtHH+3NtszbvKZUOhVl1z/E6k=
  file: "random-sleep_$TRAVIS_TAG.deb"
  on:
    repo: acondolu/random-sleep
    tag: true
