name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y libgmp-dev
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Fetch all
        run: |-
          git fetch --unshallow
          git fetch --tags --all
          git describe --tags
      - run: mkdir -p ~/.local/bin
      - run: 'export PATH=$HOME/.local/bin:$PATH'
      - run: >-
          curl -L
          https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz
          --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - run: stack --no-terminal --install-ghc test --only-dependencies
      - run: stack --no-terminal test
      - run: sh ./scripts/package.sh
      - uses: actions/upload-artifact@v4
        with:
          name: random-sleep.deb.zip
          path: random-sleep.deb
